### ISSUE TITLE
installation

### ISSUE THREAD

**Issue by wilfried18** [underloki/Cyprium#2]
Comment faire pour lancer (genre setup) pour pouvoir installer ce logiciel

**Comment by afranck64** [comment]
Salut @wilfried18 il te faut juste le télécharger (si ce n'est déjà fait) et exécuter le fichier "cyprium.py" avec Python3.X ( http://python.org/download/releases/3.3.4/ )

**Comment by wilfried18** [comment]
Je penser que c'été un logiciel a hébergé , je viens de tester c'est en ligne de commande , c'est pas encore mon truc, par contre il manque un vrai readme (option) etc

**Comment by afranck64** [comment]
Les instructions (en anglais) sont disponibles au lien suivant: [Cyprium Documentation](http://cyprium.hackademics.fr/man-cyprium-crypto-tool-open-source.php)
